### ISSUE TITLE
Static `interpolator_wandb_ckpt_filename` causes file not found error for interpolators with `num_predictions!=20`

### ISSUE THREAD

**Issue by saydemr** [Rose-STL-Lab/dyffusion#8]
Hi,

If `num_predictions` is set to some other value than 20, the code cannot find the `.ckpt` file on wandb due to static nature of  given checkpoint filenames. Readme assumes that if wandb.run_id is given for a cloud run, then the checkpoint file is automatically found. According to readme, filepath is only required for local `.ckpt` files.

Particularly [this](https://github.com/Rose-STL-Lab/dyffusion/blob/832574f6f788a0cd4a4d75e8f59b3c07c7e8446b/src/configs/diffusion/dyffusion.yaml#L14) can be changed to  `best-val_${module.num_predictions}ens_mems_ipol_avg_crps.ckpt`

Thanks.

**Comment by salvaRC** [comment]
Thank you for pointing this out! This is indeed is a bit annoying but you could always fix it by explicitly specifying ``diffusion.interpolator_wandb_ckpt_filename=<ckpt-filename-on-wandb>``, where <ckpt-filename-on-wandb> could be something like `"best-val_20ens_mems_ipol_avg_crps.ckpt"` or `"best-val_10ens_mems_ipol_avg_crps.ckpt" `or any other ckpt that you want to use.

> Particularly [this](https://github.com/Rose-STL-Lab/dyffusion/blob/832574f6f788a0cd4a4d75e8f59b3c07c7e8446b/src/configs/diffusion/dyffusion.yaml#L14) can be changed to best-val_${module.num_predictions}ens_mems_ipol_avg_crps.ckpt


The suggested fix would become a problem when the number of predictions during testing (e.g. 50) is different than what was used to validate the interpolator during its training (by default 20). Feel free to suggest alternative approaches though (e.g. modify the code that finds the ckpt on wandb to be able to search amongst all ckpts on wandb).

Let me know if you face any issues or have more suggestions!
